{
 "title": "Employee Insights Dashboard - FINAL",
 "description": "Sample dashboard using Oracle DB HR sample table",
 "time": { "from": "2011-01-13T00:00:00.000Z", "to": "2018-04-21T00:00:00.000Z" },
 "panels": [
  {
   "title": "Employee Insights",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 1 },
   "options": {
    "content": "\n\n<center><img height=300 align=\"center\" src=\"https://www.clipartkey.com/mpngs/m/162-1627477_number-of-employees-icon.png\" ></center>"
   }
  },
  {
   "title": "TOTAL Employees",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) AS TotalEmployees\nFROM HR.EMPLOYEES"
    }
   ]
  },
  { "gridPos": { "h": 9, "w": 1, "x": 9, "y": 1 } },
  {
   "title": "Total Employees Over time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 14, "x": 10, "y": 1 },
   "targets": [
    {
     "rawSql": "select hire_date, sum(count(employee_id)) over (order by hire_date rows between unbounded preceding and current row) as total_emp\nfrom hr.employees\ngroup by hire_date \norder by hire_date"
    }
   ]
  },
  { "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Employees Distribution",
   "type": "barchart",
   "gridPos": { "h": 13, "w": 10, "x": 0, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT D.DEPARTMENT_ID, D.DEPARTMENT_NAME, COUNT(*) AS TotalEmployees\nFROM HR.EMPLOYEES E\nJOIN HR.DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID\nGROUP BY D.DEPARTMENT_ID, D.DEPARTMENT_NAME\n"
    }
   ]
  },
  {
   "title": "TOTAL Employee per Country",
   "type": "geomap",
   "gridPos": { "h": 13, "w": 14, "x": 10, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT C.COUNTRY_ID, COUNT(*) AS TotalEmployees\nFROM HR.EMPLOYEES E\nJOIN HR.DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID\nJOIN HR.LOCATIONS L ON D.LOCATION_ID = L.LOCATION_ID\nJOIN HR.COUNTRIES C ON L.COUNTRY_ID = C.COUNTRY_ID\nGROUP BY C.COUNTRY_ID\n"
    }
   ]
  },
  { "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "List of Employee",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "rawSql": "SELECT *\nFROM HR.EMPLOYEES\nORDER BY HIRE_DATE DESC"
    }
   ]
  },
  {
   "title": "HR DB Schema",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "HR schema",
     "type": "text",
     "gridPos": { "h": 20, "w": 7, "x": 0, "y": 39 },
     "options": {
      "content": "The installed example data is the Oracle example HR schema database. \nDocumentation can be found here: https://docs.oracle.com/en/database/oracle/oracle-database/23/comsc/schema-diagrams.html#GUID-01BFEF14-C6BD-42CD-8558-DDD214DB3AE0__CIHGFFHI\n\n![HR Schema](https://docs.oracle.com/en/database/oracle/oracle-database/23/comsc/img/comsc008.gif)"
     }
    },
    {
     "title": "HR tables",
     "type": "table",
     "gridPos": { "h": 20, "w": 17, "x": 7, "y": 39 },
     "targets": [
      {
       "rawSql": "select tab.owner as schema_name,\n       tab.table_name as table_name,      \n       tab.num_rows\n  from all_tables tab\n where tab.owner not in ('ANONYMOUS','CTXSYS','DBSNMP','EXFSYS',\n 'LBACSYS', 'MDSYS','MGMT_VIEW','OLAPSYS','OWBSYS','ORDPLUGINS',\n 'ORDSYS','OUTLN', 'SI_INFORMTN_SCHEMA','SYS','SYSMAN','SYSTEM',\n 'TSMSYS','WK_TEST','WKSYS', 'WKPROXY','WMSYS','XDB','APEX_040000',\n 'APEX_PUBLIC_USER','DIP', 'FLOWS_30000','FLOWS_FILES','MDDATA',\n 'ORACLE_OCM','SPATIAL_CSW_ADMIN_USR', 'SPATIAL_WFS_ADMIN_USR',\n 'XS$NULL','PUBLIC')\n   and tab.owner = 'HR' \n order by tab.owner, \n       tab.table_name"
      }
     ]
    }
   ]
  }
 ]
}